package yblts;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import yblts.Bus;
import yblts.YBLTSconnectionDB;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author morales-gi
 */
public class FareMatrix extends javax.swing.JFrame {
DefaultTableModel dtm = new DefaultTableModel();
int transaction = 0;
String status = "DELETED";
String nameS;

    /**
     * Creates new form FareMatrix
     */
    public FareMatrix() {
        initComponents();
        displaytable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lfullname1 = new javax.swing.JTextField();
        lfullname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lfullname2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        authorsave1 = new javax.swing.JButton();
        authordelete = new javax.swing.JButton();
        authoredit1 = new javax.swing.JButton();
        authoredit2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        farematrixTable = new javax.swing.JTable();
        txtfarecode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt5km = new javax.swing.JTextField();
        txteffectivity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        lfullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lfullname1ActionPerformed(evt);
            }
        });

        lfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lfullnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 18, 133));
        jLabel4.setText("Succeeding Fare:");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 18, 133));
        jLabel2.setText("Bus Number:");

        lfullname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lfullname2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 18, 133));
        jLabel3.setText("Bus Class:");

        authorsave1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        authorsave1.setForeground(new java.awt.Color(37, 18, 133));
        authorsave1.setText("Save");
        authorsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorsave1ActionPerformed(evt);
            }
        });

        authordelete.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        authordelete.setForeground(new java.awt.Color(37, 18, 133));
        authordelete.setText("Delete");
        authordelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authordeleteActionPerformed(evt);
            }
        });

        authoredit1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        authoredit1.setForeground(new java.awt.Color(37, 18, 133));
        authoredit1.setText("Search");
        authoredit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authoredit1ActionPerformed(evt);
            }
        });

        authoredit2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        authoredit2.setForeground(new java.awt.Color(37, 18, 133));
        authoredit2.setText("Search");
        authoredit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authoredit2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 18, 133));
        jLabel1.setText("TICKETING SYSTEM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fare Matrix Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 720));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        farematrixTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        farematrixTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fare Matrix Code", "First 5 km", "Effectivity"
            }
        ));
        farematrixTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farematrixTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(farematrixTable);

        txtfarecode.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtfarecode.setEnabled(false);
        txtfarecode.setPreferredSize(new java.awt.Dimension(1366, 768));
        txtfarecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfarecodeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 18, 133));
        jLabel5.setText("Fair Matrix Code:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 18, 133));
        jLabel6.setText("First 5 Kilometers:");

        txt5km.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txt5km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5kmActionPerformed(evt);
            }
        });

        txteffectivity.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txteffectivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteffectivityActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 18, 133));
        jLabel7.setText("Effectivity:");

        searchbtn.setBackground(new java.awt.Color(255, 255, 255));
        searchbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(37, 18, 133));
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yblts/Search2.png"))); // NOI18N
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));

        btnsave.setBackground(new java.awt.Color(255, 255, 255));
        btnsave.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(37, 18, 133));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 255, 255));
        btndelete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(37, 18, 133));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 255, 255));
        btnexit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnexit.setForeground(new java.awt.Color(37, 18, 133));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnexit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btndelete)
                    .addComponent(btnexit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yblts/images.jpg"))); // NOI18N
        jLabel9.setText("YBL Ticketing System");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel10.setText("(YYYY/MM/DD)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt5km)
                                    .addComponent(txtfarecode, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txteffectivity, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(371, 371, 371))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(327, 327, 327))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfarecode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txteffectivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lfullnameActionPerformed

    }//GEN-LAST:event_lfullnameActionPerformed

    private void lfullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lfullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lfullname1ActionPerformed

    private void lfullname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lfullname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lfullname2ActionPerformed

    private void authorsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorsave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorsave1ActionPerformed

    private void authordeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authordeleteActionPerformed
      
    }//GEN-LAST:event_authordeleteActionPerformed

    private void authoredit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authoredit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authoredit1ActionPerformed

    private void authoredit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authoredit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authoredit2ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
       nameS = txtfarecode.getText().toString().trim();
        displayTableSearch();
        clearfields();
    }//GEN-LAST:event_searchbtnActionPerformed

    private void farematrixTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farematrixTableMouseClicked
        transaction=1;
        txtfarecode.setText(dtm.getValueAt(farematrixTable.getSelectedRow(),0).toString());
        txt5km.setText(dtm.getValueAt(farematrixTable.getSelectedRow(),1).toString());
        txteffectivity.setText(dtm.getValueAt(farematrixTable.getSelectedRow(),2).toString());
        txtfarecode.setEnabled(false);
    }//GEN-LAST:event_farematrixTableMouseClicked

    private void txteffectivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteffectivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteffectivityActionPerformed

    private void txt5kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5kmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5kmActionPerformed

    private void txtfarecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfarecodeActionPerformed

    }//GEN-LAST:event_txtfarecodeActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
        //lfullname.setText(dtm.getValueAt(tfauthor.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_btnexitActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int x = farematrixTable.getSelectedRow();
        if(txtfarecode.getText().length()>0 
                 &&txt5km.getText().length()>0
                 &&txteffectivity.getText().length()>0){
        deleteFare(dtm.getValueAt(x,0).toString());
        dtm.removeRow(farematrixTable.getSelectedRow());
        clearfields();
        
        }
        
        else JOptionPane.showMessageDialog(null,"Select row from table to delete!"); 
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        if (transaction==1)
        { 
        if(txt5km.getText().length()>0
                 &&txteffectivity.getText().length()>0){
        updatefareMatrix();
        clearfields();
        displaytable();
        txtfarecode.setEnabled(true);
        transaction=0;
        }
         else{
          JOptionPane.showMessageDialog(null,"Some Fields Are Empty");   
         }
        }
        
        else
        {       
         if(txt5km.getText().length()>0
                 &&txteffectivity.getText().length()>0){
         addfare();
         displaytable(); 
         clearfields();
         }
         else{
          JOptionPane.showMessageDialog(null,"Some Fields Are Empty");   
         }
       
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FareMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FareMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FareMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FareMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FareMatrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authordelete;
    private javax.swing.JButton authoredit1;
    private javax.swing.JButton authoredit2;
    private javax.swing.JButton authorsave1;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsave;
    private javax.swing.JTable farematrixTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lfullname;
    private javax.swing.JTextField lfullname1;
    private javax.swing.JTextField lfullname2;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField txt5km;
    private javax.swing.JTextField txteffectivity;
    private javax.swing.JTextField txtfarecode;
    // End of variables declaration//GEN-END:variables

    private void addfare() {
        
        String first5km = txt5km.getText();
        String effectivity = txteffectivity.getText();
        
  
        
        YBLTSconnectionDB d = new YBLTSconnectionDB();
        d.main();
       
        Statement stmt = null;
        String sql;
        
         try{
          stmt=d.conn.createStatement();
          sql="INSERT INTO `yellowbusdb`.`fare_matrix`(`First_5km`,`Effectivity`)VALUES('"+first5km+"','"+effectivity+"');";
         
          int success = stmt.executeUpdate(sql);
          if(success==1){
          System.out.println("success");
          }
        }catch(SQLException ex) {
              Logger.getLogger(FareMatrix.class.getName()).log(Level.SEVERE, null, ex);
              }
        
        
        
    }

    private void displaytable() {
     YBLTSconnectionDB d = new YBLTSconnectionDB();
     d.main();
  
    Statement stmt = null;
    String sql;  
        
    try {
            stmt=d.conn.createStatement();
             sql="SELECT Fare_matrix_code,First_5km,Effectivity FROM fare_matrix WHERE Status IS NULL ORDER BY Effectivity";
             ResultSet rs = stmt.executeQuery(sql);
             
             dtm = new DefaultTableModel();
             farematrixTable.setModel(dtm);
             dtm.addColumn("Fare Matrix Code");
             dtm.addColumn("First 5km");
             dtm.addColumn("Efffectivity");
             while(rs.next()){
               Object[] ob = {
               rs.getString("Fare_matrix_code"),
               rs.getString("First_5km"),
               rs.getString("Effectivity")
               };
               dtm.addRow(ob);
               
             }
        } catch (SQLException ex) {
            Logger.getLogger(FareMatrix.class.getName()).log(Level.SEVERE, null, ex);
        }     
    
    }

    private void updatefareMatrix() {
        int x = farematrixTable.getSelectedRow();
        String PK = dtm.getValueAt(x,0).toString(); 
        String fareCode = txtfarecode.getText();
        String first5km = txt5km.getText();
        String effectivity = txteffectivity.getText();
        
        YBLTSconnectionDB d = new YBLTSconnectionDB();
        d.main();
        PreparedStatement stmt = null;
        String sql;

        try {
         sql = "UPDATE `yellowbusdb`.`fare_matrix` SET `First_5km`=?,`Effectivity`=?,`Fare_matrix_code`=? WHERE `Fare_matrix_code`=?";
         stmt = d.conn.prepareStatement(sql);   
         
         
         stmt.setString(1, first5km);
         stmt.setString(2, effectivity);
         stmt.setString(3, fareCode);
         stmt.setString(4, PK);
    
         int success = stmt.executeUpdate();
         if (success == 1) {
        System.out.println("success");
         dtm.setValueAt(PK, farematrixTable.getSelectedRow(), 0);       
         dtm.setValueAt(first5km, farematrixTable.getSelectedRow(), 1);
         dtm.setValueAt(effectivity, farematrixTable.getSelectedRow(), 2);
         
         
        }}catch (SQLException ex) {
        Logger.getLogger(FareMatrix.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    private void deleteFare(String toString) {
     String[] buttons = {"YES","NO"};
    int returnValue = JOptionPane.showOptionDialog(null,"Do You Want To Delete The Records?", "NARRATIVE",
            JOptionPane.WARNING_MESSAGE,0,null,buttons,buttons);
    System.out.print(returnValue);

    if(returnValue==JOptionPane.YES_OPTION){ 
    int x = farematrixTable.getSelectedRow();
        String PK = dtm.getValueAt(x,0).toString(); 
        String id = txtfarecode.getText();
        String f5km = txt5km.getText();
        String effectivity = txteffectivity.getText();
        
        
        YBLTSconnectionDB d = new YBLTSconnectionDB();
        d.main();
        PreparedStatement stmt = null;
        String sql;
        

        try {
         //sql = "UPDATE `yellowbusdb`.`employee` SET `Employee_Fname`=?,`Employee_Mname`=?,`Emp_Lname`=?,`Job_Description`=?,`Employee_ID`=?,`Status`=? WHERE `Employee_ID`=?";       
         sql = "UPDATE `yellowbusdb`.`fare_matrix` SET `First_5km`=?,`Effectivity`=?,`Fare_matrix_code`=?,`Status`=? WHERE `Fare_matrix_code`=?";
         stmt = d.conn.prepareStatement(sql);   
         
         
         stmt.setString(1, f5km);
         stmt.setString(2, effectivity);
         stmt.setString(3, id);
         stmt.setString(4, status);
         stmt.setString(5, PK);
         
    
         int success = stmt.executeUpdate();
        
        }catch (SQLException ex) {
        Logger.getLogger(yblts.Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
      else{
        this.dispose();
        yblts.FareMatrix as = new yblts.FareMatrix();
        as.setVisible(true);
    }
    }


    private void clearfields() {
       txtfarecode.setText(null);
       txt5km.setText(null);
       txteffectivity.setText(null);  
    }

    private void displayTableSearch() {
     YBLTSconnectionDB d = new YBLTSconnectionDB();
     d.main();
  
    Statement stmt = null;
    String sql;  
        
    try {
            stmt=d.conn.createStatement();
            //sql="SELECT Employee_ID,Employee_Fname,Employee_Mname,Emp_Lname,Job_Description FROM employee WHERE Emp_Lname LIKE '"+emplname.getText().toString()+"%' AND Status IS NULL  ";
             sql="SELECT Fare_matrix_code,First_5km,Effectivity FROM fare_matrix WHERE Effectivity LIKE '"+txteffectivity.getText().toString()+"%' AND Status IS NULL ORDER BY Effectivity";
             ResultSet rs = stmt.executeQuery(sql);
             
             dtm = new DefaultTableModel();
             farematrixTable.setModel(dtm);
             dtm.addColumn("Fare Matrix Code");
             dtm.addColumn("First 5km");
             dtm.addColumn("Efffectivity");
             while(rs.next()){
               Object[] ob = {
               rs.getString("Fare_matrix_code"),
               rs.getString("First_5km"),
               rs.getString("Effectivity")
               };
               dtm.addRow(ob);
               
             }
        } catch (SQLException ex) {
            Logger.getLogger(FareMatrix.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }

    
}

