/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package yblts;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Aerole
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
     int ans = 1;
     int success = 0;
    public LogIn() {
        initComponents();
        //setVIEWfalse();
       // SERVER.setText("localhost");
       // SNAME.setText("root");
       // SPASSWORD.setText("xxxx");
       // SDBname.setText("yellobusdb");
    }

   /* public JTextField getSDBname() {
        return SDBname;
    }

    public void setSDBname(JTextField SDBname) {
        this.SDBname = SDBname;
    }

    public JTextField getSERVER() {
        return SERVER;
    }

    public void setSERVER(JTextField SERVER) {
        this.SERVER = SERVER;
    }

    public JTextField getSNAME() {
        return SNAME;
    }

    public void setSNAME(JTextField SNAME) {
        this.SNAME = SNAME;
    }

    public JTextField getSPASSWORD() {
        return SPASSWORD;
    }

    public void setSPASSWORD(JTextField SPASSWORD) {
        this.SPASSWORD = (JPasswordField) SPASSWORD;
    }*/

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public void setTxtUsername(JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMore = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        btnEditPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel11.setBackground(new java.awt.Color(255, 255, 255));
        panel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Username:");

        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Password:");

        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnLogIn.setBackground(new java.awt.Color(255, 255, 255));
        btnLogIn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnLogIn.setText("Log in");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMore.setBackground(new java.awt.Color(255, 255, 255));
        btnMore.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnMore.setText("Settings");
        btnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreActionPerformed(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnEditPassword.setBackground(new java.awt.Color(255, 255, 255));
        btnEditPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEditPassword.setText("Edit Password");
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel11Layout.createSequentialGroup()
                        .addComponent(btnMore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditPassword))
                    .addGroup(panel11Layout.createSequentialGroup()
                        .addComponent(btnLogIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)))
                .addGap(56, 56, 56))
            .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel11Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addComponent(txtUsername))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel11Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(btnExit))
                .addGap(51, 51, 51)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(btnEditPassword)
                    .addComponent(btnMore))
                .addContainerGap())
            .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel11Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed

        if(txtUsername.getText().length()==0 
                 &&txtPassword.getPassword().length ==0){
            JOptionPane.showMessageDialog(null,"Some Fields are EMPTY!");

        }
        else{

            validatePassword();
            this.dispose();
        }

    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        success = 0;
        callAdminCode();
        //SignUp as = new SignUp(this, false);
       // this.dispose();
       // as.setVisible(true);
        //setVIEWfalse();

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPasswordActionPerformed
        success = 1;
        callAdminCode();
        
    }//GEN-LAST:event_btnEditPasswordActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreActionPerformed
        String code = "nulla";
        String[] buttons = {"OK","CANCEL"};
        int op = 1;

        JTextField fileName = new JTextField();
        Object[]message = {"Admin Code",fileName.getText()};

        String option = JOptionPane.showInputDialog(null,message,"Confirmation", JOptionPane.CANCEL_OPTION);
        //System.out.println(fileName.getText());
        //String input = fileName.getText();

        JOptionPane.showMessageDialog(null,option);

        if (option == null){

            LogIn as = new LogIn();
            as.setVisible(true);

        }
        else{

            if (code.matches(option)){

                setVIEWtrue();
                Settings as = new Settings();
                as.setVisible(true);
                //ans = 2;
            }

            else{
                JOptionPane.showMessageDialog(null,"You are not an Admin!");

            }

        }

    }//GEN-LAST:event_btnMoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditPassword;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnMore;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel11;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void validatePassword() {
       String username = txtUsername.getText();
       String pass = new String (txtPassword.getPassword());      
       YBLTSconnectionDB d = new YBLTSconnectionDB();
       d.main();         
       d.validate(username, pass);     
    }

    private void setVIEWtrue() {
     btnSignUp.setEnabled(true);
     btnEditPassword.setEnabled(true);
      /*SERVER.setVisible(true);
      SNAME.setVisible(true);
      SDBname.setVisible(true);
      SPASSWORD.setVisible(true);
      SERVER.setVisible(true);
      lServer.setVisible(true);
      lPW.setVisible(true);
      lDB.setVisible(true);
      lName.setVisible(true);
      panel22.setVisible(true);*/
     
    }

    private void setVIEWfalse() {
        
     btnSignUp.setEnabled(false);
    btnEditPassword.setEnabled(false);
    /*SERVER.setVisible(false);
    SNAME.setVisible(false);
    SDBname.setVisible(false);
    SPASSWORD.setVisible(false);
    SERVER.setVisible(false);
    lServer.setVisible(false);
    lPW.setVisible(false);
    lDB.setVisible(false);
    lName.setVisible(false);
    panel22.setVisible(false);*/
   
    }
    private void callAdminCode() {
    String code = "nulla";
        String[] buttons = {"OK","CANCEL"};
        int op = 1;

        JTextField fileName = new JTextField();
        Object[]message = {"Admin Code",fileName.getText()};

        String option = JOptionPane.showInputDialog(null,message,"Confirmation", JOptionPane.CANCEL_OPTION);
        //System.out.println(fileName.getText());
        //String input = fileName.getText();

        JOptionPane.showMessageDialog(null,option);

        if (option == null){

            LogIn as = new LogIn();
            as.setVisible(true);

        }
        else{

            if (code.matches(option)){

                //setVIEWtrue();
               // Settings as = new Settings();
                //as.setVisible(true);
                //ans = 2;
                if (success == 0){
             SignUp as = new SignUp(this, false);
                this.dispose();
                as.setVisible(true);
                setVIEWfalse();
                }
                else{EditPassword as = new EditPassword(this, false);
        this.dispose();
        as.setVisible(true);
                }
            }

            else{
                JOptionPane.showMessageDialog(null,"You are not an Admin!");

            }

        }
     
    }
}
