/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package yblts;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Blythe
 */
public class Report extends javax.swing.JFrame {
    DefaultTableModel dtm = new DefaultTableModel();
int transaction = 0;
String tpass;
String tamount;
    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        txtAccount.setEnabled(false);
        txtAccount1.setEnabled(false);
        txtAccount2.setEnabled(false);
        txtAccount3.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCargo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAccountExit = new javax.swing.JButton();
        btnAccountExit1 = new javax.swing.JButton();
        btnCargoSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAccount1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAccount2 = new javax.swing.JTextField();
        txtAccount3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tnp = new javax.swing.JLabel();
        tfc = new javax.swing.JLabel();
        tnc = new javax.swing.JLabel();
        tca = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remittance Report Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1381, 720));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblCargo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bus Number", "Ticket Number", "Date Issue", "Total Amount"
            }
        ));
        tblCargo.setName("tblCargo"); // NOI18N
        tblCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCargoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCargo);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 18, 133));
        jLabel4.setText("Bus Number");

        txtAccount.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtAccount.setForeground(new java.awt.Color(37, 18, 133));
        txtAccount.setName("txtAccount"); // NOI18N
        txtAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAccountMouseClicked(evt);
            }
        });
        txtAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccountKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yblts/images.jpg"))); // NOI18N
        jLabel8.setText("YBL Ticketing System");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));

        btnAccountExit.setBackground(new java.awt.Color(255, 255, 255));
        btnAccountExit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAccountExit.setForeground(new java.awt.Color(37, 18, 133));
        btnAccountExit.setText("Exit");
        btnAccountExit.setName("btnAccountExit"); // NOI18N
        btnAccountExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountExitActionPerformed(evt);
            }
        });

        btnAccountExit1.setBackground(new java.awt.Color(255, 255, 255));
        btnAccountExit1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAccountExit1.setForeground(new java.awt.Color(37, 18, 133));
        btnAccountExit1.setText("Print");
        btnAccountExit1.setName("btnAccountExit"); // NOI18N
        btnAccountExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountExit1ActionPerformed(evt);
            }
        });

        btnCargoSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnCargoSearch.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCargoSearch.setForeground(new java.awt.Color(37, 18, 133));
        btnCargoSearch.setText("View Transation");
        btnCargoSearch.setName("btnCargoSearch"); // NOI18N
        btnCargoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargoSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargoSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccountExit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccountExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccountExit)
                    .addComponent(btnAccountExit1)
                    .addComponent(btnCargoSearch))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 18, 133));
        jLabel5.setText("From");

        txtAccount1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtAccount1.setForeground(new java.awt.Color(37, 18, 133));
        txtAccount1.setName("txtAccount"); // NOI18N
        txtAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAccount1MouseClicked(evt);
            }
        });
        txtAccount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccount1KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 18, 133));
        jLabel6.setText("To");

        txtAccount2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtAccount2.setForeground(new java.awt.Color(37, 18, 133));
        txtAccount2.setName("txtAccount"); // NOI18N
        txtAccount2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAccount2MouseClicked(evt);
            }
        });
        txtAccount2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccount2KeyPressed(evt);
            }
        });

        txtAccount3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtAccount3.setForeground(new java.awt.Color(37, 18, 133));
        txtAccount3.setName("txtAccount"); // NOI18N
        txtAccount3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAccount3MouseClicked(evt);
            }
        });
        txtAccount3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccount3KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 18, 133));
        jLabel7.setText("Conductor ID");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 18, 133));
        jLabel9.setText("Total Passenger Fare:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 18, 133));
        jLabel10.setText("Total Number of Passenger(s):");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(37, 18, 133));
        jLabel11.setText("Total Number Cargo(s):");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(37, 18, 133));
        jLabel12.setText("Total Cargo Fare:");

        tnp.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tnp.setForeground(new java.awt.Color(0, 51, 255));
        tnp.setText("jLabel1");

        tfc.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tfc.setForeground(new java.awt.Color(0, 51, 255));
        tfc.setText("jLabel1");

        tnc.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tnc.setForeground(new java.awt.Color(0, 51, 255));
        tnc.setText("jLabel1");

        tca.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tca.setForeground(new java.awt.Color(0, 51, 255));
        tca.setText("jLabel1");

        total.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(0, 51, 255));
        total.setText("jLabel1");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(37, 18, 133));
        jLabel13.setText("Total Amount:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tnp))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tnc)))
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(total))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tca))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfc)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAccount3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 163, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(tnp)
                    .addComponent(tfc))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tnc)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(tca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(total))))))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCargoMouseClicked
        /*    transaction=1;
        txtCargoCode.setText(dtm.getValueAt(tblCargo.getSelectedRow(),0).toString());
        txtCargoType.setText(dtm.getValueAt(tblCargo.getSelectedRow(),1).toString());
        txtWeight.setText(dtm.getValueAt(tblCargo.getSelectedRow(),2).toString());
        txtCargoCode.setEnabled(false);*/
    }//GEN-LAST:event_tblCargoMouseClicked

    private void txtAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccountMouseClicked
        transaction=1;
        txtAccount.setEnabled(true);
        txtAccount1.setEnabled(true);
        txtAccount2.setEnabled(true);
        txtAccount3.setEnabled(true);
    }//GEN-LAST:event_txtAccountMouseClicked

    private void txtAccountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountKeyPressed

    }//GEN-LAST:event_txtAccountKeyPressed

    private void btnAccountExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountExitActionPerformed
        Home as = new Home();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountExitActionPerformed

    private void txtAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccount1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccount1MouseClicked

    private void txtAccount1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccount1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccount1KeyPressed

    private void txtAccount2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccount2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccount2MouseClicked

    private void txtAccount2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccount2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccount2KeyPressed

    private void txtAccount3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccount3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccount3MouseClicked

    private void txtAccount3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccount3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccount3KeyPressed

    private void btnCargoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargoSearchActionPerformed
        
        if(transaction==1){
            displaySearchTable();
            display();
            displaycargo();
            displaytotal();
            txtAccount.setText(null);
            txtAccount1.setText(null);
            txtAccount2.setText(null);
            txtAccount3.setText(null);
            txtAccount.setEnabled(false);
            txtAccount1.setEnabled(false);
            txtAccount2.setEnabled(false);
            txtAccount3.setEnabled(false);
            
        }
        else{
            displayTable();
            txtAccount.setEnabled(false);
        }
    }//GEN-LAST:event_btnCargoSearchActionPerformed

    private void btnAccountExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccountExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountExit;
    private javax.swing.JButton btnAccountExit1;
    private javax.swing.JButton btnCargoSearch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCargo;
    private javax.swing.JLabel tca;
    private javax.swing.JLabel tfc;
    private javax.swing.JLabel tnc;
    private javax.swing.JLabel tnp;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtAccount1;
    private javax.swing.JTextField txtAccount2;
    private javax.swing.JTextField txtAccount3;
    // End of variables declaration//GEN-END:variables

private void displayTable() {
    transaction = 2;
     YBLTSconnectionDB d = new YBLTSconnectionDB();
     d.main();
  
    Statement stmt = null;
    String sql;  
    
   
        
    try {
            stmt=d.conn.createStatement();
            sql="SELECT Bus_Num, Ticket_Num, Date_issue, Total_Amount, Passenger_num, Cargo_code, Cargo_weight, Distance_code, Fare_matrix_code FROM ticket";          
            ResultSet rs = stmt.executeQuery(sql);
             
             dtm = new DefaultTableModel();
             tblCargo.setModel(dtm);
             dtm.addColumn("Bus Number");
             dtm.addColumn("Ticket Number");
             dtm.addColumn("Date Issue");
             dtm.addColumn("Passenger Number");
             dtm.addColumn("Total Amount");
             dtm.addColumn("Cargo Code");
             dtm.addColumn("Cargo Weight");
             dtm.addColumn("Distance Code");
             dtm.addColumn("Fare Matrix Code");
            
                         
             while(rs.next()){
               Object[] ob = {
               rs.getString("Bus_Num"),
               rs.getString("Ticket_Num"),
               rs.getString("Date_issue"),
               rs.getString("Passenger_num"),
               rs.getString("Total_Amount"),
               rs.getString("Cargo_code"),
               rs.getString("Cargo_weight"),
               rs.getString("Distance_code"),
               rs.getString("Fare_matrix_code")
               };
               dtm.addRow(ob);
               
             }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    private void clearFields() {
        txtAccount.setText(null);

    }
    
private void displaySearchTable() {
     
     YBLTSconnectionDB d = new YBLTSconnectionDB();
     d.main();
  
    Statement stmt = null;
    String sql;  
    
   
        //ticket.Bus_Num LIKE '"+txtAccount.getText().toString()+"' &&
    try {
            stmt=d.conn.createStatement();
            //sql="SELECT ticket.Bus_Num FROM ticket INNER JOIN distance_traveled ON `ticket`.`Bus_Num`=`distance_traveled`.`distance_base` WHERE ticket.Bus_Num LIKE '"+txtAccount.getText().toString()+"' ";
            //sql="SELECT ticket.Bus_Num, distance_traveled.distance_base, distance_traveled.distance_to FROM yellowbusdb.ticket JOIN yellowbusdb.distance_traveled WHERE  distance_traveled.distance_base LIKE '"+txtAccount1.getText().toString()+"' && distance_traveled.distance_to LIKE '"+txtAccount2.getText().toString()+"' ";
            /*sql="SELECT ticket.Ticket_Num, distance_traveled.distance_base, distance_traveled.distance_to, ticket.Total_Amount, ticket.Date_issue, ticket.Bus_Num,"
                    + " FROM ticket as t INNER JOIN ticket as b on b.Bus_Num = t.Bus_Num INNER JOIN distance_traveled as d on d.Distance_code=t.Distance_code"
                    + " WHERE t.Bus_Num LIKE '"+txtAccount.getText().toString()+"' && t.Employee_ID LIKE '"+txtAccount3.getText().toString()+"' ";*/
            sql="SELECT t.Ticket_Num, d.distance_base, d.distance_to, " 
            + " t.Total_Amount, t.Date_issue, t.Bus_Num FROM ticket as t "
            + " INNER JOIN distance_traveled as d on d.Distance_code=t.Distance_code" 
            + " WHERE t.Bus_Num LIKE '"+txtAccount.getText().toString()+"' "
            + "and t.Employee_ID LIKE '"+txtAccount3.getText().toString()+"'" 
            + " and d.distance_base Like '"+txtAccount1.getText().toString()+"' "
            + "and d.distance_to like '"+txtAccount2.getText().toString()+"'";
            
            ResultSet rs = stmt.executeQuery(sql);
             
             dtm = new DefaultTableModel();
             tblCargo.setModel(dtm);
             dtm.addColumn("Bus Number");
             dtm.addColumn("Ticket Number");
             dtm.addColumn("Date Issue");
             dtm.addColumn("Via From");
             dtm.addColumn("Via To");
             dtm.addColumn("Total Amount");
             
             
                         
             while(rs.next()){
               Object[] ob = {
               rs.getString("Bus_Num"),
               rs.getString("Ticket_Num"),
               rs.getString("Date_issue"),
               rs.getString("distance_base"),
               rs.getString("distance_to"),
               rs.getString("Total_Amount")        
               };
               dtm.addRow(ob);
               
             }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    transaction = 0;
    }

    private void display() {
  
     YBLTSconnectionDB d = new YBLTSconnectionDB();
     d.main();
  
    Statement stmt = null;
    String sql;  
   
    try {
            stmt=d.conn.createStatement();
            sql="SELECT count(t.Ticket_Num) as tpass, sum(t.Total_Amount) as tamount FROM ticket as t" 
            + " INNER JOIN distance_traveled as d on d.Distance_code=t.Distance_code "
            + "WHERE t.Bus_Num LIKE '"+txtAccount.getText().toString()+"' "
            + " and t.Employee_ID LIKE '"+txtAccount3.getText().toString()+"' "
            + "and d.distance_base Like '"+txtAccount1.getText().toString()+"' " 
            + "and d.distance_to like '"+txtAccount2.getText().toString()+"' "
            + "and  t.Cargo_code = 0";
            
            /* sql="SELECT t.Ticket_Num,  d.distance_base, d.distance_to, " 
            + " t.Total_Amount, t.Date_issue, t.Bus_Num FROM ticket as t "
            + " INNER JOIN distance_traveled as d on d.Distance_code=t.Distance_code" 
            + " WHERE t.Bus_Num LIKE '"+txtAccount.getText().toString()+"' "
            + "and t.Employee_ID LIKE '"+txtAccount3.getText().toString()+"'" 
            + " and d.distance_base Like '"+txtAccount1.getText().toString()+"' "
            + "and d.distance_to like '"+txtAccount2.getText().toString()+"'";*/
            
              ResultSet rs = stmt.executeQuery(sql);
             //dtm = new DefaultTableModel();
             //tblCargo1.setModel(dtm);
             //dtm.addColumn("Passenger Number");
             //dtm.addColumn("Amount");            
                         
             while(rs.next()){              
              //tpass = rs.getString("count(t.Ticket_Num)");   
              //tamount = rs.getString("sum(t.Total_Amount)");
                 
              tpass = rs.getString("tpass");   
              tamount = rs.getString("tamount");   
             }                  
               tnp.setText(tpass);
               tfc.setText(tamount);
               
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    private void displaycargo() {
    
     YBLTSconnectionDB d = new YBLTSconnectionDB();
     d.main();
  
    Statement stmt = null;
    String sql;  
   
    try {
            stmt=d.conn.createStatement();
           sql="SELECT count(t.Ticket_Num) as tpass, sum(t.Total_Amount) as tamount FROM ticket as t" 
            + " INNER JOIN distance_traveled as d on d.Distance_code=t.Distance_code "
            + "WHERE t.Bus_Num LIKE '"+txtAccount.getText().toString()+"' "
            + " and t.Employee_ID LIKE '"+txtAccount3.getText().toString()+"' "
            + "and d.distance_base Like '"+txtAccount1.getText().toString()+"' " 
            + "and d.distance_to like '"+txtAccount2.getText().toString()+"' "
            + "and  t.Cargo_code > 0";
                        
              ResultSet rs = stmt.executeQuery(sql);
             //dtm = new DefaultTableModel();
             //tblCargo1.setModel(dtm);
             //dtm.addColumn("Passenger Number");
             //dtm.addColumn("Amount");            
                         
             while(rs.next()){              
              //tpass = rs.getString("count(t.Ticket_Num)");   
              //tamount = rs.getString("sum(t.Total_Amount)");
                 
              tpass = rs.getString("tpass");   
              tamount = rs.getString("tamount");   
             }                  
               tnc.setText(tpass);
               tca.setText(tamount);
               
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }

    private void displaytotal() {
    
        YBLTSconnectionDB d = new YBLTSconnectionDB();
     d.main();
  
    Statement stmt = null;
    String sql;  
   
    try {
            stmt=d.conn.createStatement();
           sql="SELECT count(t.Ticket_Num) as tpass, sum(t.Total_Amount) as tamount FROM ticket as t" 
            + " INNER JOIN distance_traveled as d on d.Distance_code=t.Distance_code "
            + "WHERE t.Bus_Num LIKE '"+txtAccount.getText().toString()+"' "
            + " and t.Employee_ID LIKE '"+txtAccount3.getText().toString()+"' "
            + "and d.distance_base Like '"+txtAccount1.getText().toString()+"' " 
            + "and d.distance_to like '"+txtAccount2.getText().toString()+"' ";
                        
              ResultSet rs = stmt.executeQuery(sql);
             //dtm = new DefaultTableModel();
             //tblCargo1.setModel(dtm);
             //dtm.addColumn("Passenger Number");
             //dtm.addColumn("Amount");            
                         
             while(rs.next()){              
              //tpass = rs.getString("count(t.Ticket_Num)");   
              //tamount = rs.getString("sum(t.Total_Amount)");
                 
              tpass = rs.getString("tpass");   
              tamount = rs.getString("tamount");   
             }                  
               total.setText(tamount);
            
               
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
}
