/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package yblts;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Aerole
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
     int ans = 1;
    public Settings() {
        initComponents();
        //setVIEWfalse();
        SERVER.setText("localhost");
        SNAME.setText("root");
        SPASSWORD.setText("xxxx");
        SDBname.setText("yellobusdb");
    }

    public JTextField getSDBname() {
        return SDBname;
    }

    public void setSDBname(JTextField SDBname) {
        this.SDBname = SDBname;
    }

    public JTextField getSERVER() {
        return SERVER;
    }

    public void setSERVER(JTextField SERVER) {
        this.SERVER = SERVER;
    }

    public JTextField getSNAME() {
        return SNAME;
    }

    public void setSNAME(JTextField SNAME) {
        this.SNAME = SNAME;
    }

    public JTextField getSPASSWORD() {
        return SPASSWORD;
    }

    public void setSPASSWORD(JTextField SPASSWORD) {
        this.SPASSWORD = (JPasswordField) SPASSWORD;
    }

    /*public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public void setTxtUsername(JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel22 = new javax.swing.JPanel();
        lServer = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lDB = new javax.swing.JLabel();
        lPW = new javax.swing.JLabel();
        SERVER = new javax.swing.JTextField();
        SNAME = new javax.swing.JTextField();
        SDBname = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        SPASSWORD = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel22.setBackground(new java.awt.Color(255, 255, 255));
        panel22.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        lServer.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lServer.setText("SERVER:");

        lName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lName.setText("SERVER UNAME:");

        lDB.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lDB.setText("DATABASE NAME: ");

        lPW.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lPW.setText("SERVER PW:");

        SERVER.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        SNAME.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        SDBname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        SDBname.setText("yellowbusdb");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(null);

        javax.swing.GroupLayout panel22Layout = new javax.swing.GroupLayout(panel22);
        panel22.setLayout(panel22Layout);
        panel22Layout.setHorizontalGroup(
            panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel22Layout.createSequentialGroup()
                .addGroup(panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel22Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel22Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDB)
                            .addComponent(lPW)
                            .addComponent(lName)
                            .addComponent(lServer))
                        .addGap(18, 18, 18)
                        .addGroup(panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SNAME)
                            .addComponent(SERVER)
                            .addComponent(SDBname, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(SPASSWORD))))
                .addGap(16, 16, 16))
        );
        panel22Layout.setVerticalGroup(
            panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lServer)
                    .addComponent(SERVER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(SNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lPW)
                    .addGroup(panel22Layout.createSequentialGroup()
                        .addComponent(SPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(27, 27, 27)
                .addGroup(panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDB)
                    .addComponent(SDBname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SDBname;
    private javax.swing.JTextField SERVER;
    private javax.swing.JTextField SNAME;
    private javax.swing.JPasswordField SPASSWORD;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lDB;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPW;
    private javax.swing.JLabel lServer;
    private javax.swing.JPanel panel22;
    // End of variables declaration//GEN-END:variables

  /*  private void validatePassword() {
       String username = txtUsername.getText();
       String pass = new String (txtPassword.getPassword());      
       YBLTSconnectionDB d = new YBLTSconnectionDB();
       d.main();         
       d.validate(username, pass);     
    }

    private void setVIEWtrue() {
     btnSignUp.setEnabled(true);
      btnEditPassword.setEnabled(true);
      SERVER.setVisible(true);
      SNAME.setVisible(true);
      SDBname.setVisible(true);
      SPASSWORD.setVisible(true);
      SERVER.setVisible(true);
      lServer.setVisible(true);
      lPW.setVisible(true);
      lDB.setVisible(true);
      lName.setVisible(true);
      panel22.setVisible(true);
     
    }

    private void setVIEWfalse() {
        
     btnSignUp.setEnabled(false);
    btnEditPassword.setEnabled(false);
    SERVER.setVisible(false);
    SNAME.setVisible(false);
    SDBname.setVisible(false);
    SPASSWORD.setVisible(false);
    SERVER.setVisible(false);
    lServer.setVisible(false);
    lPW.setVisible(false);
    lDB.setVisible(false);
    lName.setVisible(false);
    panel22.setVisible(false);
   
    }*/
}
